// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grapheion/tenant.proto

package grapheion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebhookRequest) Reset() {
	*x = VerifyWebhookRequest{}
	mi := &file_grapheion_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebhookRequest) ProtoMessage() {}

func (x *VerifyWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebhookRequest.ProtoReflect.Descriptor instead.
func (*VerifyWebhookRequest) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VerifyWebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyWebhookResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Tenant     string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	DeployerSa string                 `protobuf:"bytes,2,opt,name=deployer_sa,json=deployerSa,proto3" json:"deployer_sa,omitempty"`
	RepoUrl    string                 `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref        string                 `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
	Path       string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Credential:
	//
	//	*VerifyWebhookResponse_GithubApp
	//	*VerifyWebhookResponse_BasicAuth
	Credential    isVerifyWebhookResponse_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebhookResponse) Reset() {
	*x = VerifyWebhookResponse{}
	mi := &file_grapheion_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebhookResponse) ProtoMessage() {}

func (x *VerifyWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebhookResponse.ProtoReflect.Descriptor instead.
func (*VerifyWebhookResponse) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyWebhookResponse) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *VerifyWebhookResponse) GetDeployerSa() string {
	if x != nil {
		return x.DeployerSa
	}
	return ""
}

func (x *VerifyWebhookResponse) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *VerifyWebhookResponse) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *VerifyWebhookResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VerifyWebhookResponse) GetCredential() isVerifyWebhookResponse_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *VerifyWebhookResponse) GetGithubApp() *GitHubAppCredential {
	if x != nil {
		if x, ok := x.Credential.(*VerifyWebhookResponse_GithubApp); ok {
			return x.GithubApp
		}
	}
	return nil
}

func (x *VerifyWebhookResponse) GetBasicAuth() *BasicAuthCredential {
	if x != nil {
		if x, ok := x.Credential.(*VerifyWebhookResponse_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

type isVerifyWebhookResponse_Credential interface {
	isVerifyWebhookResponse_Credential()
}

type VerifyWebhookResponse_GithubApp struct {
	GithubApp *GitHubAppCredential `protobuf:"bytes,10,opt,name=github_app,json=githubApp,proto3,oneof"`
}

type VerifyWebhookResponse_BasicAuth struct {
	BasicAuth *BasicAuthCredential `protobuf:"bytes,11,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

func (*VerifyWebhookResponse_GithubApp) isVerifyWebhookResponse_Credential() {}

func (*VerifyWebhookResponse_BasicAuth) isVerifyWebhookResponse_Credential() {}

type GitHubAppCredential struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	InstallationId int64                  `protobuf:"varint,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	PrivateKey     string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GitHubAppCredential) Reset() {
	*x = GitHubAppCredential{}
	mi := &file_grapheion_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubAppCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubAppCredential) ProtoMessage() {}

func (x *GitHubAppCredential) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubAppCredential.ProtoReflect.Descriptor instead.
func (*GitHubAppCredential) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *GitHubAppCredential) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GitHubAppCredential) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

func (x *GitHubAppCredential) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type BasicAuthCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuthCredential) Reset() {
	*x = BasicAuthCredential{}
	mi := &file_grapheion_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuthCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthCredential) ProtoMessage() {}

func (x *BasicAuthCredential) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthCredential.ProtoReflect.Descriptor instead.
func (*BasicAuthCredential) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *BasicAuthCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthCredential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_grapheion_tenant_proto protoreflect.FileDescriptor

const file_grapheion_tenant_proto_rawDesc = "" +
	"\n" +
	"\x16grapheion/tenant.proto\x12\tgrapheion\"N\n" +
	"\x14VerifyWebhookRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"\xa1\x02\n" +
	"\x15VerifyWebhookResponse\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1f\n" +
	"\vdeployer_sa\x18\x02 \x01(\tR\n" +
	"deployerSa\x12\x19\n" +
	"\brepo_url\x18\x03 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x04 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12?\n" +
	"\n" +
	"github_app\x18\n" +
	" \x01(\v2\x1e.grapheion.GitHubAppCredentialH\x00R\tgithubApp\x12?\n" +
	"\n" +
	"basic_auth\x18\v \x01(\v2\x1e.grapheion.BasicAuthCredentialH\x00R\tbasicAuthB\f\n" +
	"\n" +
	"credential\"v\n" +
	"\x13GitHubAppCredential\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\x03R\x0einstallationId\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\"M\n" +
	"\x13BasicAuthCredential\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2c\n" +
	"\rTenantService\x12R\n" +
	"\rVerifyWebhook\x12\x1f.grapheion.VerifyWebhookRequest\x1a .grapheion.VerifyWebhookResponseB!Z\x1fgithub.com/katastroma/grapheionb\x06proto3"

var (
	file_grapheion_tenant_proto_rawDescOnce sync.Once
	file_grapheion_tenant_proto_rawDescData []byte
)

func file_grapheion_tenant_proto_rawDescGZIP() []byte {
	file_grapheion_tenant_proto_rawDescOnce.Do(func() {
		file_grapheion_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grapheion_tenant_proto_rawDesc), len(file_grapheion_tenant_proto_rawDesc)))
	})
	return file_grapheion_tenant_proto_rawDescData
}

var file_grapheion_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grapheion_tenant_proto_goTypes = []any{
	(*VerifyWebhookRequest)(nil),  // 0: grapheion.VerifyWebhookRequest
	(*VerifyWebhookResponse)(nil), // 1: grapheion.VerifyWebhookResponse
	(*GitHubAppCredential)(nil),   // 2: grapheion.GitHubAppCredential
	(*BasicAuthCredential)(nil),   // 3: grapheion.BasicAuthCredential
}
var file_grapheion_tenant_proto_depIdxs = []int32{
	2, // 0: grapheion.VerifyWebhookResponse.github_app:type_name -> grapheion.GitHubAppCredential
	3, // 1: grapheion.VerifyWebhookResponse.basic_auth:type_name -> grapheion.BasicAuthCredential
	0, // 2: grapheion.TenantService.VerifyWebhook:input_type -> grapheion.VerifyWebhookRequest
	1, // 3: grapheion.TenantService.VerifyWebhook:output_type -> grapheion.VerifyWebhookResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grapheion_tenant_proto_init() }
func file_grapheion_tenant_proto_init() {
	if File_grapheion_tenant_proto != nil {
		return
	}
	file_grapheion_tenant_proto_msgTypes[1].OneofWrappers = []any{
		(*VerifyWebhookResponse_GithubApp)(nil),
		(*VerifyWebhookResponse_BasicAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grapheion_tenant_proto_rawDesc), len(file_grapheion_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grapheion_tenant_proto_goTypes,
		DependencyIndexes: file_grapheion_tenant_proto_depIdxs,
		MessageInfos:      file_grapheion_tenant_proto_msgTypes,
	}.Build()
	File_grapheion_tenant_proto = out.File
	file_grapheion_tenant_proto_goTypes = nil
	file_grapheion_tenant_proto_depIdxs = nil
}
