// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grapheion/tenant.proto

package grapheion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantIdentity identifies a tenant.
type TenantIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantIdentity) Reset() {
	*x = TenantIdentity{}
	mi := &file_grapheion_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantIdentity) ProtoMessage() {}

func (x *TenantIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantIdentity.ProtoReflect.Descriptor instead.
func (*TenantIdentity) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantIdentity) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type VerifyWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebhookRequest) Reset() {
	*x = VerifyWebhookRequest{}
	mi := &file_grapheion_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebhookRequest) ProtoMessage() {}

func (x *VerifyWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebhookRequest.ProtoReflect.Descriptor instead.
func (*VerifyWebhookRequest) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VerifyWebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyWebhookResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantIdentity *TenantIdentity        `protobuf:"bytes,1,opt,name=tenant_identity,json=tenantIdentity,proto3" json:"tenant_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyWebhookResponse) Reset() {
	*x = VerifyWebhookResponse{}
	mi := &file_grapheion_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebhookResponse) ProtoMessage() {}

func (x *VerifyWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebhookResponse.ProtoReflect.Descriptor instead.
func (*VerifyWebhookResponse) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyWebhookResponse) GetTenantIdentity() *TenantIdentity {
	if x != nil {
		return x.TenantIdentity
	}
	return nil
}

var File_grapheion_tenant_proto protoreflect.FileDescriptor

const file_grapheion_tenant_proto_rawDesc = "" +
	"\n" +
	"\x16grapheion/tenant.proto\x12\tgrapheion\"(\n" +
	"\x0eTenantIdentity\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"N\n" +
	"\x14VerifyWebhookRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"[\n" +
	"\x15VerifyWebhookResponse\x12B\n" +
	"\x0ftenant_identity\x18\x01 \x01(\v2\x19.grapheion.TenantIdentityR\x0etenantIdentity2c\n" +
	"\rTenantService\x12R\n" +
	"\rVerifyWebhook\x12\x1f.grapheion.VerifyWebhookRequest\x1a .grapheion.VerifyWebhookResponseB!Z\x1fgithub.com/katastroma/grapheionb\x06proto3"

var (
	file_grapheion_tenant_proto_rawDescOnce sync.Once
	file_grapheion_tenant_proto_rawDescData []byte
)

func file_grapheion_tenant_proto_rawDescGZIP() []byte {
	file_grapheion_tenant_proto_rawDescOnce.Do(func() {
		file_grapheion_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grapheion_tenant_proto_rawDesc), len(file_grapheion_tenant_proto_rawDesc)))
	})
	return file_grapheion_tenant_proto_rawDescData
}

var file_grapheion_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grapheion_tenant_proto_goTypes = []any{
	(*TenantIdentity)(nil),        // 0: grapheion.TenantIdentity
	(*VerifyWebhookRequest)(nil),  // 1: grapheion.VerifyWebhookRequest
	(*VerifyWebhookResponse)(nil), // 2: grapheion.VerifyWebhookResponse
}
var file_grapheion_tenant_proto_depIdxs = []int32{
	0, // 0: grapheion.VerifyWebhookResponse.tenant_identity:type_name -> grapheion.TenantIdentity
	1, // 1: grapheion.TenantService.VerifyWebhook:input_type -> grapheion.VerifyWebhookRequest
	2, // 2: grapheion.TenantService.VerifyWebhook:output_type -> grapheion.VerifyWebhookResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grapheion_tenant_proto_init() }
func file_grapheion_tenant_proto_init() {
	if File_grapheion_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grapheion_tenant_proto_rawDesc), len(file_grapheion_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grapheion_tenant_proto_goTypes,
		DependencyIndexes: file_grapheion_tenant_proto_depIdxs,
		MessageInfos:      file_grapheion_tenant_proto_msgTypes,
	}.Build()
	File_grapheion_tenant_proto = out.File
	file_grapheion_tenant_proto_goTypes = nil
	file_grapheion_tenant_proto_depIdxs = nil
}
