// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grapheion/tenant.proto

package grapheion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantIdentity identifies a tenant.
type TenantIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantIdentity) Reset() {
	*x = TenantIdentity{}
	mi := &file_grapheion_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantIdentity) ProtoMessage() {}

func (x *TenantIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_grapheion_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantIdentity.ProtoReflect.Descriptor instead.
func (*TenantIdentity) Descriptor() ([]byte, []int) {
	return file_grapheion_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantIdentity) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

var File_grapheion_tenant_proto protoreflect.FileDescriptor

const file_grapheion_tenant_proto_rawDesc = "" +
	"\n" +
	"\x16grapheion/tenant.proto\x12\tgrapheion\"(\n" +
	"\x0eTenantIdentity\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant2\x0f\n" +
	"\rTenantServiceB!Z\x1fgithub.com/katastroma/grapheionb\x06proto3"

var (
	file_grapheion_tenant_proto_rawDescOnce sync.Once
	file_grapheion_tenant_proto_rawDescData []byte
)

func file_grapheion_tenant_proto_rawDescGZIP() []byte {
	file_grapheion_tenant_proto_rawDescOnce.Do(func() {
		file_grapheion_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grapheion_tenant_proto_rawDesc), len(file_grapheion_tenant_proto_rawDesc)))
	})
	return file_grapheion_tenant_proto_rawDescData
}

var file_grapheion_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grapheion_tenant_proto_goTypes = []any{
	(*TenantIdentity)(nil), // 0: grapheion.TenantIdentity
}
var file_grapheion_tenant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grapheion_tenant_proto_init() }
func file_grapheion_tenant_proto_init() {
	if File_grapheion_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grapheion_tenant_proto_rawDesc), len(file_grapheion_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grapheion_tenant_proto_goTypes,
		DependencyIndexes: file_grapheion_tenant_proto_depIdxs,
		MessageInfos:      file_grapheion_tenant_proto_msgTypes,
	}.Build()
	File_grapheion_tenant_proto = out.File
	file_grapheion_tenant_proto_goTypes = nil
	file_grapheion_tenant_proto_depIdxs = nil
}
